- name: Upload SSH key
  ansible.posix.authorized_key:
    comment: ''
    exclusive: yes
    key: "{{ lookup('file', ssh_public_key_path) }}"
    manage_dir: yes
    user: ubuntu

- name: Enable passwordless sudo
  ansible.builtin.copy:
    src: sudoers
    dest: /etc/sudoers.d/users
    mode: 0440

- name: Add "ubuntu" user to "users" group
  ansible.builtin.user:
    name: ubuntu
    groups: users
    append: yes

- name: Disable default ubuntu user password
  ansible.builtin.user:
    name: ubuntu
    password: '!'

- name: Disable password login
  ansible.builtin.lineinfile:
    path: "{{ sshd_config }}"
    regexp: ^#?PasswordAuthentication
    line: PasswordAuthentication no

- name: Disable empty password login
  ansible.builtin.lineinfile:
    path: "{{ sshd_config }}"
    regexp: ^#?PermitEmptyPasswords
    line: PermitEmptyPasswords no

- name: Disable remote root login
  ansible.builtin.lineinfile:
    path: "{{ sshd_config }}"
    regexp: ^#?PermitRootLogin
    line: PermitRootLogin no
