---
apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: {{ kubernetes_control_plane_advertise_address }}
nodeRegistration:
  name: {{ inventory_hostname }}
  criSocket: unix:///var/run/containerd.sock
  taints: []
skipPhases:
- addon/coredns
- addon/kube-proxy
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
kubernetesVersion: v{{ kubernetes_version }}
clusterName: kubernetes
controlPlaneEndpoint: {{ kubernetes_control_plane_address }}:{{ kubernetes_control_plane_port }}
apiServer:
  certSANs:
  - localhost
  - {{ kubernetes_control_plane_address }}
networking:
  dnsDomain: {{ kubernetes_cluster_domain }}
  podSubnet: {{ kubernetes_networking_pod_subnet }}
  serviceSubnet: {{ kubernetes_networking_service_subnet }}
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
clusterDNS:
- {{ kubernetes_cluster_dns }}
clusterDomain: {{ kubernetes_cluster_domain }}
containerRuntimeEndpoint: unix:///var/run/containerd.sock
serverTLSBootstrap: true
