- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    install_recommends: no
    update_cache: yes
  loop:
  - bluez
  - dbus-broker

- name: Start services
  ansible.builtin.service:
    enabled: yes
    name: "{{ item }}"
    state: started
  loop:
  - dbus-broker

- name: Copy files
  ansible.builtin.copy:
    src: configuration.yaml
    dest: /srv/home-assistant/configuration.yaml

- name: Start Home Assistant container
  shell: |
    if [ -n "$(docker container list --all --quiet --filter name=home-assistant)" ]; then
      docker container stop home-assistant
      docker container rm -v home-assistant
    fi

    docker container run \
      --detach \
      --env TZ={{ system_timezone }} \
      --name home-assistant \
      --network host \
      --restart unless-stopped \
      --volume /run/dbus:/run/dbus:ro \
      --volume /srv/home-assistant:/config \
      ghcr.io/home-assistant/home-assistant:2022.11.4
