- name: Start Home Assistant container
  shell: |
    if [ -n "$(docker container list --all --quiet --filter name=home-assistant)" ]; then
      docker container stop home-assistant
      docker container rm -v home-assistant
    fi

    docker container run \
      --detach \
      --env TZ={{ system_timezone }} \
      --name home-assistant \
      --network host \
      --restart unless-stopped \
      --volume /srv/home-assistant:/config \
      ghcr.io/home-assistant/home-assistant:2022.7.2
