- name: Start UniFi container
  shell: |
    if [ -n "$(docker container list --all --quiet --filter name=unifi-controller)" ]; then
      docker container stop unifi-controller
      docker container rm -v unifi-controller
    fi

    docker container run \
      --detach \
      --env MEM_LIMIT=1024M \
      --env PGID=1000 \
      --env PUID=1000 \
      --env TZ={{ system_timezone }} \
      --init \
      --name unifi-controller \
      --network host \
      --restart unless-stopped \
      --volume /srv/unifi-controller:/config \
      linuxserver/unifi-controller:7.1.66-ls157
