- hosts: controller
  become: yes
  roles:
  - role: system/os
  - role: system/security
  - role: system/zerotier
  - role: containerd/os
  - role: containerd/containerd
  - role: docker/os
  - role: docker/docker
  - role: containers/adguard-home
  - role: containers/syncthing-relay
  - role: containers/unbound
  - role: containers/unifi-controller
  - role: system/upgrade
