- hosts: controller
  become: yes
  gather_facts: yes
  roles:
  - role: system/base
  - role: system/security
  - role: zerotier
  - role: docker
  - role: containers/adguard-home
  - role: containers/syncthing-relay
  - role: containers/unbound
  - role: containers/unifi-controller
  - role: system/upgrade
