- hosts: controller
  become: yes
  gather_facts: yes
  roles:
  - role: system
  - role: security
  - role: zerotier
  - role: docker
  - role: adguard-home
  - role: unbound
  - role: unifi-controller
  - role: upgrade
