- hosts: home
  become: yes
  gather_facts: yes
  roles:
  - role: system
  - role: security
  - role: zerotier
  - role: docker
  - role: containers/home-assistant
  - role: containers/unbound
  - role: upgrade
