- hosts: home
  become: yes
  roles:
  - role: system/os
  - role: system/security
  - role: zerotier
  - role: docker
  - role: containers/home-assistant
  - role: containers/unbound
  - role: system/upgrade
