- hosts: kubernetes
  become: yes
  roles:
  - role: system/os
  - role: system/security
  - role: system/zerotier
  - role: containerd/os
  - role: containerd/containerd
  - role: docker/os
  - role: docker/docker
  - role: kubernetes/os
  - role: kubernetes/kubernetes
  - role: system/upgrade
