- hosts: all
  become: yes
  roles:
  - role: system/os
  - role: system/security
  - role: system/cloudflared
  - role: system/tailscale
  - role: system/upgrade
  tags:
  - nodes

- hosts: docker
  become: yes
  roles:
  - role: containerd/os
  - role: containerd/containerd
  - role: docker/os
  - role: docker/docker
  tags:
  - docker

- hosts: primary
  become: yes
  roles:
  - role: containerd/os
  - role: containerd/containerd
  - role: kubernetes/os
  - role: kubernetes/kubernetes
  - role: kubernetes/primary
  tags:
  - kubernetes-primary

- hosts: masters
  become: yes
  roles:
  - role: containerd/os
  - role: containerd/containerd
  - role: kubernetes/os
  - role: kubernetes/kubernetes
  - role: kubernetes/masters
  tags:
  - kubernetes-master

- hosts: workers
  become: yes
  roles:
  - role: containerd/os
  - role: containerd/containerd
  - role: kubernetes/os
  - role: kubernetes/kubernetes
  - role: kubernetes/workers
  tags:
  - kubernetes-worker
