- name: Ensure directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
  - /etc/kubernetes/kubeadm

- name: Copy certificates
  ansible.builtin.copy:
    force: false
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
  - src: ca.crt
    dest: /etc/kubernetes/pki/ca.crt
  - src: ca.key
    dest: /etc/kubernetes/pki/ca.key

- name: Copy files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
  - src: kubeadm.yaml
    dest: /etc/kubernetes/kubeadm/init.yaml
  - src: manifest.yaml
    dest: /etc/kubernetes/kubeadm/manifest.yaml

- name: Start services
  ansible.builtin.service:
    enabled: yes
    name: "{{ item }}"
    state: started
  loop:
  - kubelet

- name: Initialize Kubernetes cluster
  ansible.builtin.command: kubeadm init --config /etc/kubernetes/kubeadm/init.yaml
  args:
    creates: /etc/kubernetes/pki/apiserver.key

- name: Setup Kubernetes Components
  ansible.builtin.command: kubectl apply -f /etc/kubernetes/kubeadm/manifest.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Fetch Kubeconfig
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: ./kubeconfig
    flat: yes
