- name: Setup Hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname | capitalize }}"

- name: Setup Timezone
  community.general.timezone:
    hwclock: UTC
    name: "{{ system_timezone }}"

- name: Setup Locale
  community.general.locale_gen:
    name: "{{ system_locale }}"

- name: Install Essential Packages
  ansible.builtin.apt:
    install_recommends: no
    name: "{{ item }}"
    update_cache: yes
  loop:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg2
  - openssh-server
  - software-properties-common
  - sudo

- name: Setup Kernel Module (tcp_bbr)
  community.general.modprobe:
    name: "{{ item }}"
  loop:
  - tcp_bbr

- name: Persist Kernel Modules
  ansible.builtin.copy:
    dest: /etc/modules-load.d/network.conf
    content: |
      tcp_bbr

- name: Configure Kernel Parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
  - name: fs.inotify.max_user_watches
    value: 524288
  - name: net.core.default_qdisc
    value: fq
  - name: net.ipv4.tcp_congestion_control
    value: bbr

- name: Start Services (ssh & timesyncd)
  ansible.builtin.service:
    enabled: yes
    name: "{{ item }}"
    state: started
  loop:
  - ssh
  - systemd-timesyncd
