- name: Setup hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Setup timezone
  community.general.timezone:
    hwclock: UTC
    name: "{{ system_timezone }}"

- name: Setup locale
  community.general.locale_gen:
    name: "{{ system_locale }}"

- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    install_recommends: no
    update_cache: yes
  loop:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg2
  - openssh-server
  - software-properties-common
  - sudo

- name: Setup kernel modules
  community.general.modprobe:
    name: "{{ item }}"
  loop:
  - tcp_bbr

- name: Persist kernel modules
  ansible.builtin.copy:
    dest: /etc/modules-load.d/{{ item }}.conf
    content: "{{ item }}"
  loop:
  - tcp_bbr

- name: Configure kernel parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
  - name: fs.inotify.max_user_watches
    value: 524288
  - name: net.core.default_qdisc
    value: fq
  - name: net.ipv4.tcp_congestion_control
    value: bbr

- name: Start service
  ansible.builtin.service:
    enabled: yes
    name: "{{ item }}"
    state: started
  loop:
  - ssh
  - systemd-timesyncd
