- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop:
  - apt-transport-https
  - bluez
  - ca-certificates
  - curl
  - dbus-broker
  - gnupg2
  - locales
  - openssh-server
  - software-properties-common
  - sudo
  - unzip

- name: Setup hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Setup timezone
  community.general.timezone:
    hwclock: UTC
    name: "{{ system_timezone }}"

- name: Setup locale
  community.general.locale_gen:
    name: "{{ system_locale }}"

- name: Setup kernel modules
  community.general.modprobe:
    name: "{{ item }}"
  loop:
  - tcp_bbr

- name: Persist kernel modules
  ansible.builtin.copy:
    dest: /etc/modules-load.d/{{ item }}.conf
    content: "{{ item }}"
  loop:
  - tcp_bbr

- name: Configure kernel parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
  - name: fs.inotify.max_user_instances
    value: 16384
  - name: fs.inotify.max_user_watches
    value: 1048576
  - name: net.core.default_qdisc
    value: fq
  - name: net.core.rmem_max
    value: 2621400
  - name: net.ipv4.conf.all.rp_filter
    value: 1
  - name: net.ipv4.ip_forward
    value: 1
  - name: net.ipv4.ip_nonlocal_bind
    value: 1
  - name: net.ipv4.tcp_congestion_control
    value: bbr
  - name: net.ipv6.ip_nonlocal_bind
    value: 1
  - name: vm.max_map_count
    value: 262144

- name: Start services
  ansible.builtin.service:
    enabled: yes
    name: "{{ item }}"
    state: started
  loop:
  - dbus-broker
  - ssh
  - systemd-timesyncd
