- name: Start Home Assistant container
  shell: |
    _=$(docker container inspect home-assistant &>/dev/null)
    echo $?
    _=$(docker container inspect home-assistant &>/dev/null)

    if [ $? -eq 0 ]; then
      docker container stop home-assistant
      docker container rm -v home-assistant
    fi

    docker container run \
      --detach \
      --env TZ="{{ system_timezone }}" \
      --init \
      --name home-assistant \
      --network host \
      --restart unless-stopped \
      --volume /srv/home-assistant:/config \
      homeassistant/home-assistant:0.103.5
