- name: Create directory
  file:
    group: root
    mode: 0755
    owner: root
    path: /tmp/vscode-server
    state: directory

- name: Create VSCode Server directory
  file:
    group: 1000
    mode: 0755
    owner: 1000
    path: /srv/vscode-server
    state: directory

- name: Copy files
  ansible.builtin.copy:
    src: Dockerfile
    dest: /tmp/vscode-server/Dockerfile

- name: Build & start VSCode Server container
  shell: |
    docker build -t vscode-server /tmp/vscode-server

    if [ -n "$(docker container list --all --quiet --filter name=vscode-server)" ]; then
      docker container stop vscode-server
      docker container rm -v vscode-server
    fi

    docker container run \
      --detach \
      --env TZ={{ system_timezone }} \
      --env VSCODE_CLI_DATA_DIR=/opt/vscode-server \
      --mount source=/srv/syncthing/codespaces,target=/home/vscode/codespaces,type=bind,consistency=cached \
      --mount source=/srv/syncthing/dotfiles,target=/home/vscode/.dotfiles,type=bind,consistency=cached \
      --mount source=dev-tunnel-git,target=/home/vscode/.git,type=volume \
      --mount source=dev-tunnel-gpg,target=/home/vscode/.gnupg,type=volume \
      --mount source=dev-tunnel-ssh,target=/home/vscode/.ssh,type=volume \
      --mount source=dev-vscode-docker,target=/home/vscode/.docker,type=volume \
      --mount source=dev-vscode-kubernetes,target=/home/vscode/.kube,type=volume \
      --name vscode-server \
      --network host \
      --restart unless-stopped \
      --user vscode \
      --volume /srv/vscode-server:/opt/vscode-server \
      vscode-server --accept-server-license-terms --name={{ vscode_server_name }}

- name: Link dotfiles
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
  - src: /srv/syncthing/dotfiles/.docker
    dest: /var/lib/docker/volumes/dev-vscode-docker/_data
  - src: /srv/syncthing/dotfiles/.kubernetes
    dest: /var/lib/docker/volumes/dev-vscode-kubernetes/_data

- name: Clean up
  ansible.builtin.file:
    path: /tmp/vscode-server
    state: absent
