- name: Ensure directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
  - /opt/cni/bin
  - /usr/lib/systemd/system

- name: Download CNI files
  ansible.builtin.get_url:
    url: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  loop:
  - src: https://raw.githubusercontent.com/containernetworking/plugins/refs/heads/main/plugins/ipam/dhcp/systemd/cni-dhcp.socket
    dest: /usr/lib/systemd/system/cni-dhcp.socket
  - src: https://raw.githubusercontent.com/containernetworking/plugins/refs/heads/main/plugins/ipam/dhcp/systemd/cni-dhcp.service
    dest: /usr/lib/systemd/system/cni-dhcp.service

- name: Extract CNI plugins
  ansible.builtin.unarchive:
    dest: /opt/cni/bin/
    remote_src: yes
    src: "https://github.com/containernetworking/plugins/releases/download/v{{ cni_plugins_version }}/cni-plugins-linux-{{ cni_plugins_architecture }}-v{{ cni_plugins_version }}.tgz"
  args:
    creates: /opt/cni/bin/README.md

- name: Start services
  ansible.builtin.service:
    enabled: yes
    name: "{{ item }}"
    state: started
  loop:
  - cni-dhcp
