- name: Add APT key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker-apt-keyring.gpg

- name: Add APT repository
  ansible.builtin.apt_repository:
    filename: docker
    repo: deb [arch={{ docker_architecture }} signed-by=/etc/apt/keyrings/docker-apt-keyring.gpg] https://download.docker.com/linux/ubuntu {{ docker_apt_release }} stable

- name: Ensure directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
  - /etc/docker
  - /usr/lib/systemd/system/docker.service.d
  - /usr/lib/systemd/system/docker.socket.d

- name: Copy files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
  - src: ca.pem
    dest: /etc/docker/ca.pem
  - src: cert.pem
    dest: /etc/docker/cert.pem
  - src: key.pem
    dest: /etc/docker/key.pem
  - src: service.conf
    dest: /usr/lib/systemd/system/docker.service.d/override.conf
  - src: socket.conf
    dest: /usr/lib/systemd/system/docker.socket.d/override.conf

- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop:
  - docker-ce
  - docker-ce-cli

- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop:
  - docker-scan-plugin
  when: install_docker_scan_plugin | bool

- name: Start services
  ansible.builtin.service:
    enabled: yes
    name: "{{ item }}"
    state: started
  loop:
  - docker
