- name: Add APT key
  ansible.builtin.apt_key:
    url: https://pkg.cloudflare.com/cloudflare-main.gpg
    keyring: /etc/apt/keyrings/cloudflare-archive-keyring.gpg

- name: Add APT repository
  ansible.builtin.apt_repository:
    filename: cloudflare
    repo: deb [arch={{ cloudflare_architecture }} signed-by=/etc/apt/keyrings/cloudflare-archive-keyring.gpg] https://pkg.cloudflare.com/cloudflared {{ cloudflare_apt_release }} main

- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop:
  - cloudflared

- name: Enable cloudflared
  ansible.builtin.command: cloudflared service install {{ cloudflare_tunnel_token }}
  args:
    creates: /etc/systemd/system/cloudflared*
  when:
  - cloudflare_tunnel_token is defined

- name: Start services
  ansible.builtin.service:
    enabled: yes
    name: "{{ item }}"
    state: started
  loop:
  - cloudflared
