- name: Add APT key
  ansible.builtin.apt_key:
    url: https://pkgs.tailscale.com/stable/ubuntu/focal.noarmor.gpg
    keyring: /etc/apt/keyrings/tailscale-archive-keyring.gpg

- name: Add APT repository
  ansible.builtin.apt_repository:
    filename: tailscale
    repo: deb [arch={{ tailscale_architecture }} signed-by=/etc/apt/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu {{ tailscale_apt_release }} main

- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop:
  - tailscale

- name: Join Tailnet
  ansible.builtin.command: tailscale up --accept-dns=false --advertise-routes={{ tailscale_advertise_routes }} --auth-key={{ tailscale_auth_key }} --ssh
  when:
  - tailscale_auth_key is defined

- name: Start services
  ansible.builtin.service:
    enabled: yes
    name: "{{ item }}"
    state: started
  loop:
  - tailscaled
