- name: Add APT key
  ansible.builtin.apt_key:
    url: https://apt.kubernetes.io/doc/apt-key.gpg
    keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg

- name: Add APT repository
  ansible.builtin.apt_repository:
    filename: kubernetes
    repo: deb [arch={{ kubernetes_architecture }} signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io {{ kubernetes_apt_release }} main

- name: Ensure directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
  - /etc/cni/net.d
  - /etc/kubernetes/kubeadm
  - /etc/kubernetes/manifests
  - /etc/kubernetes/pki
  - /usr/lib/systemd/system/kubelet.service.d
  - /var/lib/kube-router

- name: Copy files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
  - src: 10-kuberouter.conflist
    dest: /etc/cni/net.d/10-kuberouter.conflist
  - src: crictl.yaml
    dest: /etc/crictl.yaml
  - src: ca.crt
    dest: /etc/kubernetes/pki/ca.crt
  - src: ca.key
    dest: /etc/kubernetes/pki/ca.key
  - src: service.conf
    dest: /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf

- name: Copy files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
  - src: manifest-coredns.yaml
    dest: /etc/kubernetes/kubeadm/manifest-coredns.yaml
  - src: manifest-kube-router.yaml
    dest: /etc/kubernetes/kubeadm/manifest-kube-router.yaml
  - src: kubeadm-init.yaml
    dest: /etc/kubernetes/kubeadm/init.yaml
  - src: kube-router-kubeconfig.yaml
    dest: /var/lib/kube-router/kubeconfig

- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    install_recommends: no
    update_cache: yes
  loop:
  - kubeadm
  - kubectl
  - kubelet

- name: Start services
  ansible.builtin.service:
    enabled: yes
    name: "{{ item }}"
    state: started
  loop:
  - kubelet

- name: Initialize Kubernetes cluster
  ansible.builtin.command: kubeadm init --config /etc/kubernetes/kubeadm/init.yaml
  args:
    creates: /etc/kubernetes/pki/apiserver.key

- name: Setup Kubernetes Components
  ansible.builtin.command: kubectl apply -f /etc/kubernetes/kubeadm/manifest-{{ item }}.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  loop:
  - coredns
  - kube-router

- name: Fetch Kubeconfig
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: ./kubeconfig
    flat: yes
