- name: Add APT key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker-archive-keyring.gpg

- name: Add APT key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /etc/apt/keyrings/kubernetes-archive-keyring.gpg

- name: Add APT repository
  ansible.builtin.apt_repository:
    filename: docker
    repo: deb [arch={{ containerd_architecture }} signed-by=/etc/apt/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ containerd_apt_release }} stable

- name: Add APT repository
  ansible.builtin.apt_repository:
    filename: kubernetes
    repo: deb [arch={{ kubernetes_architecture }} signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io {{ kubernetes_apt_release }} main

- name: Ensure directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
  - /etc/cni/net.d
  - /etc/containerd

- name: Copy files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
  - src: config.toml
    dest: /etc/containerd/config.toml
  - src: containerd.conflist
    dest: /etc/cni/net.d/30-containerd.conflist

- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop:
  - containerd.io
  - kubernetes-cni

- name: Start services
  ansible.builtin.service:
    enabled: yes
    name: "{{ item }}"
    state: started
  loop:
  - containerd
