- name: Start UniFi container
  shell: |
    _=$(docker container inspect unifi-controller &>/dev/null)

    if [ $? -eq 0 ]; then
      docker container stop unifi-controller
      docker container rm -v unifi-controller
    fi

    docker container run \
      --detach \
      --env MEM_LIMIT=1024M \
      --env PGID=1000 \
      --env PUID=1000 \
      --env TZ="{{ system_timezone }}" \
      --init \
      --name unifi-controller \
      --network host \
      --restart unless-stopped \
      --volume /srv/unifi-controller:/config \
      linuxserver/unifi-controller:5.12.35-ls49
