- name: Overwrite release repository for Ubuntu
  set_fact:
    docker_deb_release_repo: bionic
  when:
  - ansible_facts.distribution == 'Ubuntu'
  - ansible_facts.distribution_major_version | int > 18

- name: Add Docker GPG key
  apt_key:
    id: "{{ docker_gpg_key_id }}"
    keyserver: "{{ docker_gpg_key_server }}"

- name: Add Docker APT repository
  apt_repository:
    repo: "deb {{ docker_download_base_url }}/linux/{{ docker_deb_repo }} {{ docker_deb_release_repo }} stable"
    filename: docker

- name: Install Docker packages
  apt:
    install_recommends: no
    name: "{{ item }}"
    update_cache: yes
  loop:
  - containerd.io
  - docker-ce
  - docker-ce-cli

- name: Install Docker for Python
  pip:
    extra_args: --upgrade
    name:
    - docker

- name: Start Docker services
  service:
    enabled: yes
    name: docker
    state: started
