- name: Start AdGuard Home container
  shell: |
    if [ -n "$(docker container list --all --quiet --filter name=adguard-home)" ]; then
      docker container stop adguard-home
      docker container rm -v adguard-home
    fi

    docker container run \
      --detach \
      --env TZ={{ system_timezone }} \
      --init \
      --name adguard-home \
      --network host \
      --restart unless-stopped \
      --volume /srv/adguard-home/conf:/opt/adguardhome/conf \
      --volume /srv/adguard-home/work:/opt/adguardhome/work \
      adguard/adguardhome:v0.107.21
