- name: Ensure "docker" group exists
  ansible.builtin.group:
    name: docker
    gid: 990
    state: present

- name: Add "ubuntu" user to "docker" group
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: yes
