---
apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
discovery:
  file:
    kubeConfigPath: /etc/kubernetes/kubeadm/kubeconfig
nodeRegistration:
  name: {{ inventory_hostname }}
  criSocket: unix:///var/run/containerd.sock
  taints: []
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
clusterDNS:
- {{ kubernetes_cluster_dns }}
clusterDomain: {{ kubernetes_cluster_domain }}
containerRuntimeEndpoint: unix:///var/run/containerd.sock
serverTLSBootstrap: true
