- name: Setup kernel modules
  community.general.modprobe:
    name: "{{ item }}"
  loop:
  - br_netfilter
  - bridge
  - overlay

- name: Persist kernel modules
  ansible.builtin.copy:
    dest: /etc/modules-load.d/{{ item }}.conf
    content: "{{ item }}"
  loop:
  - br_netfilter
  - bridge
  - overlay
  - rbd

- name: Configure kernel parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
  - name: net.bridge.bridge-nf-call-arptables
    value: 1
  - name: net.bridge.bridge-nf-call-iptables
    value: 1
  - name: net.bridge.bridge-nf-call-ip6tables
    value: 1

- name: Configure boot options
  block:
  - name: Check GRUB
    ansible.builtin.stat:
      path: /etc/default/grub
    register: grub

  - name: Check U-Boot
    ansible.builtin.stat:
      path: /boot/firmware/config.txt
    register: uboot

  - name: Configure boot options (GRUB)
    block:
    - name: Copy files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
      - src: 90-cgroups.cfg
        dest: /etc/default/grub.d/90-cgroups.cfg
    - name: Update GRUB
      ansible.builtin.command: update-grub
    when: grub.stat.exists

  - name: Configure boot options (U-Boot)
    block:
    - name: Copy files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
      - src: cmdline.txt
        dest: /boot/firmware/cmdline.txt
    - name: Update boot configurations
      ansible.builtin.lineinfile:
        path: /boot/firmware/config.txt
        line: cmdline=cmdline.txt
        state: present

    when: uboot.stat.exists
