- name: Setup kernel modules
  community.general.modprobe:
    name: "{{ item }}"
  loop:
  - br_netfilter
  - bridge
  - overlay

- name: Persist mernel modules
  ansible.builtin.copy:
    dest: /etc/modules-load.d/{{ item }}.conf
    content: "{{ item }}"
  loop:
  - br_netfilter
  - bridge
  - overlay

- name: Configure kernel parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
  - name: net.bridge.bridge-nf-call-arptables
    value: 1
  - name: net.bridge.bridge-nf-call-iptables
    value: 1
  - name: net.bridge.bridge-nf-call-ip6tables
    value: 1
  - name: net.ipv4.conf.all.rp_filter
    value: 1
  - name: net.ipv4.ip_forward
    value: 1
  - name: net.ipv4.ip_nonlocal_bind
    value: 1
  - name: vm.max_map_count
    value: 262144
