default_config:

frontend:
  themes: !include_dir_merge_named themes

http:
  use_x_forwarded_for: true
  trusted_proxies:
  - 192.168.0.0/16

automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
