default_config:

fan:
- platform: template
  fans:
    bedroom:
      unique_id: bedroom_fan
      oscillating_template: "{{ states('input_select.bedroom_fan_oscillating') if is_state('input_boolean.bedroom_fan_power', 'on') else False }}"
      percentage_template: "{{ states('input_number.bedroom_fan_speed') if is_state('input_boolean.bedroom_fan_power', 'on') else 0 }}"
      value_template: "{{ states('input_boolean.bedroom_fan_power') }}"
      speed_count: 7
      turn_on:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.bedroom_fan_power
      turn_off:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.bedroom_fan_power
      set_oscillating:
      - service: input_select.select_option
        target:
          entity_id: input_select.bedroom_fan_oscillating
        data:
          option: "{{ oscillating }}"
      set_percentage:
      - service: input_boolean.turn_{{ 'on' if percentage > 0 else 'off' }}
        target:
          entity_id: input_boolean.bedroom_fan_power
      - service: input_number.set_value
        target:
          entity_id: input_number.bedroom_fan_speed
        data:
          value: "{{ percentage }}"

frontend:
  themes: !include_dir_merge_named themes

http:
  use_x_forwarded_for: true
  trusted_proxies:
  - 192.168.0.0/16

automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
