- name: Add APT key
  ansible.builtin.apt_key:
    url: https://download.zerotier.com/contact@zerotier.com.gpg
    keyring: /etc/apt/keyrings/zerotier-archive-keyring.gpg

- name: Add APT repository
  ansible.builtin.apt_repository:
    filename: zerotier
    repo: deb [arch={{ zerotier_architecture }} signed-by=/etc/apt/keyrings/zerotier-archive-keyring.gpg] https://download.zerotier.com/debian/{{ zerotier_apt_release }} {{ zerotier_apt_release }} main

- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    install_recommends: no
    update_cache: yes
  loop:
  - zerotier-one

- name: Join ZeroTier network
  ansible.builtin.command: zerotier-cli join {{ zerotier_network_id }}
  args:
    creates: /var/lib/zerotier-one/networks.d/{{ zerotier_network_id }}.conf
  when:
  - zerotier_network_id is defined

- name: Start services
  ansible.builtin.service:
    enabled: yes
    name: "{{ item }}"
    state: started
  loop:
  - zerotier-one
