- name: Install containerd
  block:
  - name: Create Workspace
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
    loop:
    - /etc/containerd
    - /tmp/containerd

  - name: Download containerd
    ansible.builtin.get_url:
      checksum: sha256:https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/cri-containerd-cni-{{ containerd_version }}-linux-{{ containerd_architecture }}.tar.gz.sha256sum
      dest: /tmp/containerd.tar.gz
      url: https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/cri-containerd-cni-{{ containerd_version }}-linux-{{ containerd_architecture }}.tar.gz

  - name: Extract containerd
    ansible.builtin.unarchive:
      src: /tmp/containerd.tar.gz
      dest: /tmp/containerd
      remote_src: yes

  - name: Install containerd
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      remote_src: yes
    loop:
    - src: /tmp/containerd/usr/local/bin/
      dest: /bin/
    - src: /tmp/containerd/usr/local/sbin/
      dest: /bin/

  - name: Copy Files for containerd
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    loop:
    - src: config.toml
      dest: /etc/containerd/config.toml
    - src: containerd.service
      dest: /lib/systemd/system/containerd.service

  - name: Clean Up
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    loop:
    - /tmp/containerd
    - /tmp/containerd.tar.gz

- name: Start containerd
  ansible.builtin.service:
    enabled: yes
    name: "{{ item }}"
    state: started
  loop:
  - containerd
