- name: Add APT key
  ansible.builtin.apt_key:
    url: https://syncthing.net/release-key.gpg
    keyring: /usr/share/keyrings/syncthing-archive-keyring.gpg

- name: Add APT repository
  ansible.builtin.apt_repository:
    filename: syncthing
    repo: deb [arch={{ syncthing_architecture }} signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net {{ syncthing_apt_release }} stable

- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    install_recommends: no
    update_cache: yes
  loop:
  - syncthing

- name: Ensure directories
  ansible.builtin.file:
    group: users
    owner: ubuntu
    mode: 0775
    state: directory
    path: "{{ item }}"
  loop:
  - /home/syncthing

- name: Start service
  ansible.builtin.service:
    enabled: yes
    name: "{{ item }}"
    state: started
  loop:
  - syncthing@ubuntu
